name: Build PR
on:
  pull_request:

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, windows-latest]
    name: Build Desktop App
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: build desktop
        run: |
          npm config set -g production false
          npm i -g @ionic/cli
          make build-desktop

  build-android:
    name: "Build Android App"
    runs-on: "ubuntu-20.04"
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: build Android App
      run: |
        npm config set -g production false
        npm i -g @ionic/cli
        make build-android

  build-docs:
    name: "Build Docs"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
          extended: true

      - name: Build
        run: cd documentation && hugo --minify --theme book
